### ISSUE TITLE
Unsupported/unrecognized library keys don't produce errors

### ISSUE THREAD

**Issue by vmrob** [ccbrown/needy#91] opened 2016-07-28 21:37 UTC
The following project won't produce any errors (assuming `foo` exists and has something in it).

```
libraries:
    foo:
        directory: foo
        asdfasdf:
            - echo hello
```

**Comment by ccbrown** [comment] 2016-07-28 21:37
This is a duplicate of #38 .

**Closed by ccbrown** 2016-07-28 21:37 UTC
